POST http://localhost:5000/api/register
Content-Type: application/json

{
  "mName" : "Shloka",
  "mEmail" : "shloka@gmail.com",
  "mContact" : "0429429425",
  "mPassword" : "Shlokaaaa12!"
}
###

POST http://localhost:5000/api/login
Content-Type: application/json

{
  "mEmail": "shloka@gmail.com",
  "mPassword": "Shlokaaaa12!"
}
###

POST http://localhost:5000/api/createRestaurant
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtRW1haWwiOiJzaGxva2FAZ21haWwuY29tIiwiaWF0IjoxNjg4OTk2NDg1fQ.v8K5g-JrF1fxWj4NuuFEGqPqbS1ttZu843ZvFaKtvQk
Content-Type: application/json

{
  "rName": "Restaurant Intro",
  "rLocation": "Pendle Hill",
  "rDescription": "Eat for free if you're jobless",
  "rContact": "426429232",
  "rTableCount": 6,
  "rImage" : "https://img.rawpixel.com/private/static/images/website/2022-05/upwk61661577-wikimedia-image-kowapeej.jpg?w=800&dpr=1&fit=default&crop=default&q=65&vib=3&con=3&usm=15&bg=F4F4F3&ixlib=js-2.2.1&s=14769aec7c86811c0c7e4eb29fa4a76e"
}

###
GET http://localhost:5000/api/getRestaurant
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtRW1haWwiOiJqb2huZG9lMUBleGFsZS5jb20iLCJpYXQiOjE2ODg0MTkzMTB9.unLoZofxKeqKvJvYMSbMnGq7gjLgkfqVXXC4ZA4O_Yk
 
###
PUT http://localhost:5000/api/editRestaurant
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtRW1haWwiOiJqb2huZG9lMUBleGFsZS5jb20iLCJpYXQiOjE2ODg0MTkzMTB9.unLoZofxKeqKvJvYMSbMnGq7gjLgkfqVXXC4ZA4O_Yk
Content-Type: application/json

{
  "resId" : "Store: 8",
  "rName": "Restaurant Namw",
  "rLocation": "Restaurant sdfdsfLocation",
  "rDescription": "Restaurant sdfsdfsdfDescription",
  "rContact": "426429232",
  "rTableCount": 2
}

###

POST http://localhost:5000/api/addCategory/Res2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtRW1haWwiOiJzaGxva2FAZ21haWwuY29tIiwiaWF0IjoxNjg4OTk2NDg1fQ.v8K5g-JrF1fxWj4NuuFEGqPqbS1ttZu843ZvFaKtvQk
Content-Type: application/json

{
  "cName": "Morning Sunshine",
  "cDescription": "Hashbrowns and Muffins",
  "cType": "BreakFast",
  "cImage": "https://img.rawpixel.com/private/static/images/website/2022-05/upwk61661577-wikimedia-image-kowapeej.jpg?w=800&dpr=1&fit=default&crop=default&q=65&vib=3&con=3&usm=15&bg=F4F4F3&ixlib=js-2.2.1&s=14769aec7c86811c0c7e4eb29fa4a76e"
}

###
GET http://localhost:5000/api/getCategory/Res2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtRW1haWwiOiJzaGxva2FAZ21haWwuY29tIiwiaWF0IjoxNjg4OTk2NDg1fQ.v8K5g-JrF1fxWj4NuuFEGqPqbS1ttZu843ZvFaKtvQk


###
PUT http://localhost:5000/api/editCategory/Res2/Cat1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtRW1haWwiOiJzaGxva2FAZ21haWwuY29tIiwiaWF0IjoxNjg5MDkzMzQ1fQ.E9TT2hjrlRjdNTF198jLmWqGdai8IMKTecmjNtzytWY
Content-Type: application/json

{
  "cName": "Evening Chats Edited1",
  "cDescription": "Beers and Pongs",
  "cType": "Snacks and Drinks Edited",
  "cImage": "https://img.rawpixel.com/private/static/images/website/2022-05/upwk61661577-wikimedia-image-kowapeej.jpg?w=800&dpr=1&fit=default&crop=default&q=65&vib=3&con=3&usm=15&bg=F4F4F3&ixlib=js-2.2.1&s=14769aec7c86811c0c7e4eb29fa4a76e"
}

###
DELETE http://localhost:5000/api/deleteCategory/Res2/Cat1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtRW1haWwiOiJzaGxva2FAZ21haWwuY29tIiwiaWF0IjoxNjg5MDkzMzQ1fQ.E9TT2hjrlRjdNTF198jLmWqGdai8IMKTecmjNtzytWY

###
POST http://localhost:5000/api/addItems/Res2/Cat2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtRW1haWwiOiJzaGxva2FAZ21haWwuY29tIiwiaWF0IjoxNjg5MDkzMzQ1fQ.E9TT2hjrlRjdNTF198jLmWqGdai8IMKTecmjNtzytWY
Content-Type: application/json

{
  "iName" : "CHicken BIryani",
  "iPrice" : "240",
  "iDescription" : "Succulent Chicken with beautifully aromatic dum rice",
  "iIngredients" : "Chicken, Rice, Salt, Love",
  "iImage" : "https://img.rawpixel.com/private/static/images/website/2022-05/upwk61661577-wikimedia-image-kowapeej.jpg?w=800&dpr=1&fit=default&crop=default&q=65&vib=3&con=3&usm=15&bg=F4F4F3&ixlib=js-2.2.1&s=14769aec7c86811c0c7e4eb29fa4a76e"
  
}

###
GET http://localhost:5000/api/getItems/Res2/Cat2
